name: state_management
description: Shopping cart examples with different state management implementation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_riverpod: ^1.0.4
  provider: ^6.0.3
  riverpod: ^1.0.3

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
